version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Install dependencies
          command: |
            poetry install
      - run:
          name: Run Pylint
          command: |
            poetry run pylint devchat tests
      - run:
          name: Run Pytest
          command: |
            poetry run pytest

workflows:
  version: 2
  build:
    jobs:
      - build
